name: Test pip

on:
  release:
    types: [published]

jobs:
  Test_run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-2019]
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
    - name: git pull
      uses: actions/checkout@v1
      with:
        ref: dev
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pyexiv2
        python -m pip install pytest psutil
    - name: Test
      run: |
        cd .github
        cd workflows
        python test_pip.py
